# config.toml

[paths]
ocrdir   = "data/interim/ocr_text"
normdir  = "data/interim/normalized_text"
parsedir = "data/interim/parsed"

[ocr]
languages      = ["en"]
gpu            = false
min_confidence = 0.6
paragraph      = false
dpi            = 300

[logging]
level = "INFO"   # DEBUG, INFO, WARNING, ERROR
